# config/settings.py
# Colores y configuración global

COLOR_PRIMARIO = "#2E7D32"
COLOR_PRIMARIO_OSCURO = "#1B4620"
COLOR_SECUNDARIO = "#1565C0"
COLOR_SECUNDARIO_OSCURO = "#0D47A1"
COLOR_FONDO = "#1E1E1E"
COLOR_PANEL = "#2D2D2D"
COLOR_TEXTO = "#FFFFFF"
COLOR_TEXTO_SECUNDARIO = "#CCCCCC"
COLOR_ERROR = "#D32F2F"

RUTA_DB = "fittrack.db"